"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { useSession } from "@/hooks/useSession";
import { certificateApi, Certificate, Milestone } from "@/lib/api";
import { Upload, FileText, Plus, CheckCircle2, Trophy, MoreVertical, ExternalLink } from "lucide-react";

// Local UI-specific extensions if needed, otherwise use the API types.
interface DisplayMilestone extends Milestone {
  desc: string; icon: string; category: string;
  current_pct: number; can_generate: boolean; already_earned: boolean;
}

interface DisplayCertificate extends Certificate {
  issuer: string; type: string; issued_at: string;
}

export default function CertificatesPage() {
  const { data: session } = useSession();
  const [certificates, setCertificates] = useState<DisplayCertificate[]>([]);
  const [milestones, setMilestones] = useState<DisplayMilestone[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [uploading, setUploading] = useState(false);
  const [showUpload, setShowUpload] = useState(false);
  const [uploadTitle, setUploadTitle] = useState("");
  const [uploadFile, setUploadFile] = useState<File | null>(null);


  const fetchCertificates = async () => {
    setLoading(true);
    try {
      const token = typeof window !== "undefined" ? localStorage.getItem("token") || "" : "";
      
      const data = await certificateApi.list(token);
      setCertificates((data.certificates as unknown as DisplayCertificate[]) || []);
      setMilestones((data.milestones as unknown as DisplayMilestone[]) || []);
    } catch (e) {
      setError("Neural engine is optimizing. Please refresh in a few seconds.");
    } finally { setLoading(false); }
  };

  const generateCertificate = async (milestoneId: string) => {
    setGenerating(milestoneId); setError(""); setSuccess("");
    try {
      const token = typeof window !== "undefined" ? localStorage.getItem("token") || "" : "";
      const data = await certificateApi.generate(milestoneId, token);
      setSuccess(data.message || "🎉 Certificate generated!");
      fetchCertificates();
    } catch (e: unknown) {
      const error = e as Error;
      setError(error.message || "Failed to generate certificate.");
    } finally { setGenerating(null); }
  };

  const handleUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadFile || !uploadTitle) return;
    setUploading(true); setError(""); setSuccess("");
    try {
      const token = typeof window !== "undefined" ? localStorage.getItem("token") || "" : "";
      await certificateApi.uploadFile(uploadFile, uploadTitle, token);
      setSuccess("🚀 Certificate uploaded to your private vault!");
      setShowUpload(false); setUploadFile(null); setUploadTitle("");
      fetchCertificates();
    } catch (e: any) { setError(e.message || "Upload failed"); }
    finally { setUploading(false); }
  };

  useEffect(() => { 
    if (session) fetchCertificates(); 
  }, [session]);

  const formatDate = (iso: string) => new Date(iso).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const CATEGORY_COLOR: Record<string, string> = {
    coding: "#4ECDC4", interview: "#FFD93D", roadmap: "#43E97B", videos: "#6C63FF",
  };

  return (
    <div style={{ maxWidth: 1000, margin: "0 auto", paddingBottom: 60 }}>
      <div style={{ marginBottom: 40, display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 20 }}>
        <div>
          <div style={{ padding: "6px 12px", borderRadius: 30, background: "rgba(139,92,246,0.1)", border: "1px solid rgba(139,92,246,0.2)", fontSize: 10, fontWeight: 900, color: "#8B5CF6", letterSpacing: 1.5, marginBottom: 12, display: "inline-block" }}>
            CREDENTIAL VAULT
          </div>
          <h1 style={{ fontSize: "clamp(28px, 5vw, 44px)", fontWeight: 900, fontFamily: "var(--font-outfit)", letterSpacing: "-1.5px", marginBottom: 12 }}>
            Universal <span className="gradient-text">Certificates</span>
          </h1>
          <p style={{ color: "var(--text-secondary)", fontSize: 17, maxWidth: 600 }}>
            Managed verified credentials. Generated by Tulasi AI or uploaded from your global portfolio.
          </p>
        </div>
        <button onClick={() => setShowUpload(true)} className="btn-primary" 
          style={{ padding: "14px 28px", borderRadius: 16, fontWeight: 900, fontSize: 14, display: "flex", alignItems: "center", gap: 10, background: "white", color: "black", boxShadow: "0 10px 20px rgba(255,255,255,0.1)" }}>
          <Plus size={18} /> Upload External
        </button>
      </div>

      {showUpload && (
        <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
          style={{ marginBottom: 40, padding: 32, borderRadius: 24, background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", position: "relative" }}>
          <div style={{ fontSize: 12, fontWeight: 900, color: "var(--text-muted)", marginBottom: 20 }}>UPLOAD EXTERNAL CREDENTIAL (PDF/JPG)</div>
          <form onSubmit={handleUpload} style={{ display: "grid", gridTemplateColumns: "1fr 1fr auto", gap: 16, alignItems: "flex-end" }}>
            <div>
              <label style={{ fontSize: 11, fontWeight: 900, color: "var(--text-secondary)", display: "block", marginBottom: 8 }}>CERTIFICATE TITLE</label>
              <input value={uploadTitle} onChange={e => setUploadTitle(e.target.value)} placeholder="e.g. AWS Certified Developer" className="input-field" style={{ width: "100%", borderRadius: 12 }} />
            </div>
            <div>
              <label style={{ fontSize: 11, fontWeight: 900, color: "var(--text-secondary)", display: "block", marginBottom: 8 }}>SELECT FILE</label>
              <input type="file" onChange={e => setUploadFile(e.target.files?.[0] || null)} className="input-field" style={{ width: "100%", borderRadius: 12, padding: "8px 12px" }} />
            </div>
            <div style={{ display: "flex", gap: 12 }}>
              <button type="submit" disabled={uploading || !uploadFile} className="btn-primary" style={{ padding: "14px 32px", borderRadius: 12, fontWeight: 900 }}>
                {uploading ? "Syncing..." : "Sync Portfolio"}
              </button>
              <button type="button" onClick={() => setShowUpload(false)} style={{ background: "none", border: "none", color: "var(--text-muted)", fontSize: 13, fontWeight: 800, cursor: "pointer" }}>Cancel</button>
            </div>
          </form>
        </motion.div>
      )}

      {error && (
        <div style={{ background: "rgba(255,107,107,0.1)", border: "1px solid rgba(255,107,107,0.3)", borderRadius: 12, padding: "14px 18px", color: "#FF6B6B", marginBottom: 24, fontSize: 14 }}>
          ⚠️ {error}
        </div>
      )}
      {success && (
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          style={{ background: "rgba(67,233,123,0.1)", border: "1px solid rgba(67,233,123,0.3)", borderRadius: 12, padding: "14px 18px", color: "#43E97B", marginBottom: 24, fontSize: 14 }}>
          ✅ {success}
        </motion.div>
      )}

      {/* Earned Certificates */}
      {!loading && certificates.length > 0 && (
        <div style={{ marginBottom: 48 }}>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 20 }}>🏆 Your Earned Certificates ({certificates.length})</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 20 }}>
            {certificates.map((cert, i) => (
              <motion.div key={cert.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}
                style={{
                  background: "linear-gradient(135deg, rgba(255,215,0,0.08), rgba(255,140,0,0.05))",
                  border: "1px solid rgba(255,215,0,0.3)", borderRadius: 18, padding: 24,
                  position: "relative", overflow: "hidden",
                }}>
                <div style={{ position: "absolute", top: -20, right: -20, fontSize: 80, opacity: 0.06 }}>🎓</div>

                <div style={{ fontSize: 32, marginBottom: 12 }}>🏅</div>
                <div style={{ fontSize: 16, fontWeight: 800, color: "white", marginBottom: 6 }}>{cert.title}</div>
                <div style={{ fontSize: 13, color: "#FFD700", fontWeight: 600, marginBottom: 12 }}>{cert.issuer}</div>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <span style={{ fontSize: 11, color: "var(--text-muted)" }}>Issued {formatDate(cert.issued_at)}</span>
                  <span style={{ background: "rgba(255,215,0,0.15)", color: "#FFD700", padding: "2px 10px", borderRadius: 8, fontSize: 11, fontWeight: 700 }}>✓ Verified</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      )}

      {/* Milestones */}
      <div>
        <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>🎯 Progress Milestones</h2>
        <p style={{ color: "var(--text-secondary)", fontSize: 13, marginBottom: 24 }}>
          Reach 100% to unlock a certificate. Certificates are <strong>strictly progress-gated</strong> — no shortcuts.
        </p>

        {loading ? (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 20 }}>
            {[1, 2, 3, 4].map(k => (
              <div key={k} style={{ height: 180, background: "rgba(255,255,255,0.03)", borderRadius: 16, border: "1px solid rgba(255,255,255,0.05)" }} />
            ))}
          </div>
        ) : (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 20 }}>
            {milestones.map((m, i) => {
              const categoryStr = String(m.category || "");
              const color = CATEGORY_COLOR[categoryStr] || "#6C63FF";
              const locked = !m.can_generate;
              const earned = m.already_earned;
              return (
                <motion.div key={m.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                  className="dash-card"
                  style={{
                    padding: 24,
                    background: earned ? "rgba(255,215,0,0.05)" : locked ? "rgba(255,255,255,0.02)" : "rgba(78,205,196,0.06)",
                    border: earned ? "1px solid rgba(255,215,0,0.3)" : locked ? "1px solid rgba(255,255,255,0.06)" : `1px solid ${color}50`,
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 14 }}>
                    <span style={{ fontSize: 32 }}>{earned ? "🏅" : locked ? "🔒" : "🔓"} {m.icon}</span>
                    <span style={{ fontSize: 11, fontWeight: 700, padding: "3px 10px", borderRadius: 8,
                      background: earned ? "rgba(255,215,0,0.15)" : locked ? "rgba(255,255,255,0.05)" : `${color}20`,
                      color: earned ? "#FFD700" : locked ? "var(--text-muted)" : color }}>
                      {earned ? "✓ EARNED" : `${m.current_pct}%`}
                    </span>
                  </div>
                  <h3 style={{ fontSize: 15, fontWeight: 800, color: earned ? "#FFD700" : "white", marginBottom: 6 }}>{m.title}</h3>
                  <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 16, lineHeight: 1.5 }}>{m.desc}</p>

                  {/* Progress bar */}
                  <div style={{ height: 6, background: "rgba(255,255,255,0.08)", borderRadius: 6, marginBottom: 16, overflow: "hidden" }}>
                    <motion.div
                      initial={{ width: 0 }} animate={{ width: `${m.current_pct}%` }} transition={{ duration: 1, delay: i * 0.1 + 0.3 }}
                      style={{ height: "100%", background: earned ? "#FFD700" : locked ? "rgba(255,255,255,0.2)" : `linear-gradient(90deg, ${color}, ${color}aa)`, borderRadius: 6 }}
                    />
                  </div>

                  {!earned && (
                    <motion.button
                      whileHover={m.can_generate ? { scale: 1.03 } : {}}
                      whileTap={m.can_generate ? { scale: 0.97 } : {}}
                      onClick={() => m.can_generate && generateCertificate(m.id)}
                      disabled={!m.can_generate || generating === m.id}
                      style={{
                        width: "100%", padding: "10px", borderRadius: 10, border: "none", cursor: m.can_generate ? "pointer" : "default",
                        background: m.can_generate ? `linear-gradient(135deg, ${color}, #6C63FF)` : "rgba(255,255,255,0.05)",
                        color: m.can_generate ? "white" : "var(--text-muted)", fontWeight: 700, fontSize: 14,
                        opacity: generating === m.id ? 0.7 : 1,
                      }}
                    >
                      {generating === m.id ? "Generating..." : m.can_generate ? "🎓 Generate Certificate" : `🔒 Need ${100 - Number(m.current_pct || 0)}% more`}
                    </motion.button>
                  )}
                  {earned && (
                    <button
                      onClick={() => {
                        const handleDownload = async () => {
                          try {
                            // Dynamically import to prevent SSR errors
                            const html2pdf = (await import('html2pdf.js')).default;
                            
                            const container = document.createElement("div");
                            container.innerHTML = `
                              <div style="width: 900px; height: 600px; padding: 4px; background: linear-gradient(135deg, #FFD700 0%, #B8860B 50%, #FFD700 100%); border-radius: 8px; font-family: 'Outfit', sans-serif;">
                                <div style="background: #0A0A0B; width: 100%; height: 100%; border-radius: 6px; box-sizing: border-box; padding: 60px; text-align: center; position: relative; border: 1px solid rgba(255,215,0,0.2);">
                                  <div style="font-size: 16px; letter-spacing: 6px; color: #DAA520; text-transform: uppercase; margin-bottom: 40px; font-weight: 700;">Tulasi AI Platform</div>
                                  <div style="font-size: 14px; color: #888; text-transform: uppercase; letter-spacing: 3px; margin-bottom: 12px;">Certificate of Achievement</div>
                                  <div style="font-size: 42px; font-weight: 900; color: white; margin: 10px 0 20px; font-family: 'Outfit', sans-serif;">${session?.user?.name || session?.user?.email || "Tulasi AI Student"}</div>
                                  <div style="width: 400px; height: 1px; background: linear-gradient(90deg, transparent, #FFD700, transparent); margin: 0 auto 30px;"></div>
                                  <div style="font-size: 14px; color: #888; text-transform: uppercase; letter-spacing: 3px; margin-bottom: 12px;">has successfully mastered</div>
                                  <div style="font-size: 32px; font-weight: 800; color: #FFD700; margin-bottom: 12px;">${m.title}</div>
                                  <div style="font-size: 15px; color: #aaa; line-height: 1.6; max-width: 600px; margin: 0 auto 50px;">${m.desc}</div>
                                  <div style="display: flex; justify-content: space-between; align-items: flex-end; margin-top: 20px;">
                                    <div style="text-align: center; width: 200px;">
                                      <div style="font-family: cursive; font-size: 24px; color: #ccc; margin-bottom: 5px;">Tulasi Admin</div>
                                      <div style="border-top: 1px solid #444; padding-top: 8px; font-size: 12px; color: #666; font-weight: 700; text-transform: uppercase;">Authorized Signatory</div>
                                    </div>
                                    <div style="width: 80px; height: 80px; border: 2px solid #DAA520; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 10px; color: #DAA520; font-weight: 900; transform: rotate(-15deg); background: rgba(218,165,32,0.05);">OFFICIAL<br/>VERIFIED</div>
                                    <div style="text-align: center; width: 200px;">
                                      <div style="font-size: 12px; color: #DAA520; font-weight: 700; margin-bottom: 10px;">${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</div>
                                      <div style="border-top: 1px solid #444; padding-top: 8px; font-size: 12px; color: #666; font-weight: 700; text-transform: uppercase;">Date of Issuance</div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            `;
                            
                            // Temporarily append to body to render fonts correctly
                            container.style.position = 'absolute';
                            container.style.left = '-9999px';
                            document.body.appendChild(container);
                            
                            const opt: any = {
                              margin: 0,
                              filename: `${m.title.replace(/\s+/g, "_")}_Certificate.pdf`,
                              image: { type: 'jpeg', quality: 0.98 },
                              html2canvas: { scale: 2, useCORS: true, backgroundColor: '#050505' },
                              jsPDF: { unit: 'px', format: [900, 600], orientation: 'landscape' }
                            };
                            
                            await html2pdf().set(opt).from(container).save();
                            document.body.removeChild(container);
                          } catch (err) {
                            console.error("PDF Generation failed:", err);
                            alert("Failed to generate PDF. Check console.");
                          }
                        };
                        handleDownload();
                      }}
                      style={{ width: "100%", padding: "10px", borderRadius: 10, background: "rgba(255,215,0,0.1)", border: "1px solid rgba(255,215,0,0.3)", color: "#FFD700", fontWeight: 700, cursor: "pointer" }}
                    >
                      📥 Download Certificate
                    </button>
                  )}
                </motion.div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
