"""Add pgvector and document states

Revision ID: 8d508de83359
Revises: 01b8a04984d0
Create Date: 2026-09-10 19:07:42.385556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.models.custom_types


# revision identifiers, used by Alembic.
revision: str = '8d508de83359'
down_revision: Union[str, Sequence[str], None] = '01b8a04984d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;') if op.get_bind().dialect.name == 'postgresql' else None
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentchunk', sa.Column('embedding', app.models.custom_types.VectorType(), nullable=True))
    op.add_column('documentchunk', sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('documentchunk', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documentchunk', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('usermemorychunk', sa.Column('embedding', app.models.custom_types.VectorType(), nullable=True))
    op.drop_column('usermemorychunk', 'embedding_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermemorychunk', sa.Column('embedding_json', sa.VARCHAR(), nullable=False))
    op.drop_column('usermemorychunk', 'embedding')
    op.drop_column('documentchunk', 'updated_at')
    op.drop_column('documentchunk', 'created_at')
    op.drop_column('documentchunk', 'metadata_json')
    op.drop_column('documentchunk', 'embedding')
    # ### end Alembic commands ###
